task_name: preference
label_name: label

train_data_path: ./synthetic_preference_train.json
val_data_path: ./synthetic_preference_val.json
test_data_path: ./synthetic_preference_test.json

prompt_templates:
  observations:
    multi_content: |
      Here's a tweet from a person:
      Tweet: ${text}
      
      This person has a preference for: ${label}
    
  few_shot_prefix: |
    We have seen some examples:

  initialize_zero_shot:
    system: |-
      You are a social media platform moderator. You need to determine the preference of a user based on their tweet.
      Based on your past experiences, please generate hypotheses that are useful for predicting the preference of a user based on their tweet.
      
      These hypotheses should identify patterns in the tweet that predict preferences.
      Please propose ${num_hypotheses} refined hypotheses and generate them in the format of 1. [hypothesis], 2. [hypothesis], ... ${num_hypotheses}. [hypothesis].
      
    user: |-
      Please generate hypotheses that are useful for predicting the preference of a user based on their tweet.
      Please propose ${num_hypotheses} possible hypotheses.

      Generate them in the format of 1. [hypothesis], 2. [hypothesis], ... ${num_hypotheses}. [hypothesis]. 

      Proposed hypotheses:

  batched_generation:
    system: |-
      You are a social media platform moderator. You need to determine the preference of a user based on their tweet.
      Given a set of users' tweets, we want to generate hypotheses that are useful for predicting the preference of a user based on their tweet.

      Your task is to identify what patterns or traits show up more in people with each of the preference types. Focus on the generalizable insight that can be applied in other contexts. Ignore things that are specific to this dataset. Do not make references to this dataset as they may not be applicable to others.

      Using the given examples, please propose ${num_hypotheses} possible hypothesis pairs.
      When proposing hypotheses, look closely into the given examples and identify specific patterns that occur across the provided tweet examples. 
      The hypotheses should be clear, easy to understand, and have specific details such that one can apply the hypotheses to predict the preference of a user based on their tweet.

      Generate them in the format of 1. [hypothesis], 2. [hypothesis], ... ${num_hypotheses}. [hypothesis].
      The hypotheses should analyze what patterns or traits show up more in people with each of the preference types.

    user: |-
      We have seen some examples:
      ${observations}
      Please generate hypotheses that are useful for predicting the preference of a user based on their tweet.
      Propose ${num_hypotheses} possible hypotheses. Generate them in the format of 1. [hypothesis], 2. [hypothesis], ... ${num_hypotheses}. [hypothesis].
      
      When proposing hypotheses, look closely into the given examples and identify specific patterns that occur across the provided tweet examples. 

      Please make sure that the hypotheses are:
      i. clear (i.e., precise, not too wordy, and easy to understand);
      ii. generalizable to novel situations (i.e., they would make sense if applied to other tweet prediction experiments or other contexts);
      iii. empirically plausible (i.e., this is a dimension on which students can vary on);
      iv. usable (i.e., a human equipped with this insight could use it to predict a new user's preference based on their tweet in a similar way).

      Proposed hypotheses:
  IO_refine_with_feedback:
    system: |-
      
    user: |-
      Applying your rule to the following inputs does not produce the expected outputs.
      Here's your proposed hypothesis: ${hypothesis_text}
      Below is some examples that you predicted wrong using the hypothesis.
      ${observations}
      Please generate new hypotheses that maps the given inputs to their corresponding outputs.
      Propose ${num_hypotheses} possible hypotheses. Generate them in the format of 1. [hypothesis], 2. [hypothesis], ... ${num_hypotheses}. [hypothesis].

  few_shot_baseline:
    system: |-
      You are a social media platform moderator. You need to determine the preference of a user based on their tweet.
      You will see a tweet, and you need to predict the preference of the user.
      Give an answer. The answer should be one of the preferences (Outdoor Enthusiast, Tech-Savvy Consumer, Health-Conscious Eater).
      You must give your final answer in the format of "Final answer: ANSWER"

    user: |-
      ${few_shot_prefix}${observations}
      Here's a tweet from a person:
      Tweet: ${text}

      Given the tweet, predict the preference of the user.
      You must give your final answer in the format of "Final answer: ANSWER".

  inference:
    system: |-
      You are a social media platform moderator. You need to determine the preference of a user based on their tweet.
      From past experiences, you learned a pattern. 
      You need to determine whether each of the patterns holds for the current user tweet, and also predict the preference of the user.
      Give an answer. The answer should be one of the preferences (Outdoor Enthusiast, Tech-Savvy Consumer, Health-Conscious Eater).
      You must give your final answer in the format of "Final answer: ANSWER"

    user: |-
      Our learned patterns: ${hypothesis}                          
      New tweet:
      Here's a tweet from a person:
      Tweet: ${text}

      Given the pattern you learned above, give an answer of the preference of the user.
      Think step by step.
      First step: Think about which pattern can be applied to the tweet.
      Second step: Based on the pattern, what is the preference of the user?
      You must give your final answer in the format of "Final answer: ANSWER". Do not use markdown around your answer.
      
  multiple_hypotheses_inference:
    system: |-
      You are a social media platform moderator. You need to determine the preference of a user based on their tweet.
      From past experiences, you learned some patterns. 
      You need to determine whether each of the patterns holds for the current tweet, and also predict the preference of the user.
      Give an answer. The answer should be one of the preferences (Outdoor Enthusiast, Tech-Savvy Consumer, Health-Conscious Eater).
      Give your final answer in the format of "Final answer: ANSWER"
    user: |-
      Our learned patterns: ${hypotheses}                          
      New tweet:
      Here's a tweet from a person:
      Tweet: ${text}

      Given the patterns you learned above, give an answer of the preference of the user.
      Think step by step.
      First step: Think about which pattern can be applied to the tweet.
      Second step: Based on the pattern, what is the preference of the user?
      You must give your final answer in the format of "Final answer: ANSWER". Do not use markdown around your answer.
